### ISSUE TITLE
ESP-IDF 5.0 support

### ISSUE THREAD

**Issue by 20162026** [plasmapper/esp-cpp#1]
Are there any plans to port these libraries for IDF 5.0+? Or not until it's officially released?

Stuff that fails to build:

- espidf components are no longer included into custom components by default
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/build-system.html#specify-component-requirements-explicitly

- uint32_t was changed to be unsigned long instead of int and %u %d now result in a warning/error
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/gcc.html#espressif-toolchain-changes

- esp_eth api changed esp_eth_mac_new_esp32 now requires 2 parameters instead of one

There could be more breaking changes as I did not test the whole lib yet.

**Comment by plasmapper** [comment]
Right now I cosider these libraries more or less in the development stage. Once IDF 5.0 is stable I plan to make them dependent on it. And I suppose that by that time IDF Component Registry is open for public contributions, so I can upload it there to have better installation and versioning capbilities.

**Comment by plasmapper** [comment]
I updated the component dependencies and code for the IDF v5.0.
